import { addMonths, addDays, subMonths } from 'date-fns';
import type { Database } from './database.types';

type Subscription = Database['public']['Tables']['subscriptions']['Row'];

export const demoSubscriptions: Omit<Subscription, 'id' | 'user_id' | 'created_at' | 'updated_at'>[] = [
  {
    name: 'Netflix Premium',
    domain: 'netflix.com',
    category: 'Streaming',
    amount: 15.49,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 5).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 8).toISOString(),
    email_address: 'info@account.netflix.com',
    cancellation_url: 'https://www.netflix.com/cancelplan',
    is_demo: true,
  },
  {
    name: 'Spotify Premium',
    domain: 'spotify.com',
    category: 'Streaming',
    amount: 10.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 12).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 24).toISOString(),
    email_address: 'noreply@spotify.com',
    cancellation_url: 'https://www.spotify.com/account/subscription/',
    is_demo: true,
  },
  {
    name: 'Adobe Creative Cloud',
    domain: 'adobe.com',
    category: 'SaaS',
    amount: 54.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 3).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 15).toISOString(),
    email_address: 'message@adobe.com',
    cancellation_url: 'https://account.adobe.com/',
    is_demo: true,
  },
  {
    name: 'ChatGPT Plus',
    domain: 'openai.com',
    category: 'SaaS',
    amount: 20.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 18).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 6).toISOString(),
    email_address: 'noreply@openai.com',
    cancellation_url: 'https://platform.openai.com/account/billing',
    is_demo: true,
  },
  {
    name: 'Notion Plus',
    domain: 'notion.so',
    category: 'SaaS',
    amount: 10.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 25).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 10).toISOString(),
    email_address: 'team@makenotion.com',
    cancellation_url: 'https://www.notion.so/my-account',
    is_demo: true,
  },
  {
    name: 'GitHub Pro',
    domain: 'github.com',
    category: 'SaaS',
    amount: 4.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 8).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 18).toISOString(),
    email_address: 'noreply@github.com',
    cancellation_url: 'https://github.com/settings/billing',
    is_demo: true,
  },
  {
    name: 'Figma Professional',
    domain: 'figma.com',
    category: 'SaaS',
    amount: 144.00,
    currency: 'USD',
    billing_cycle: 'annual',
    next_payment_date: addMonths(new Date(), 2).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 10).toISOString(),
    email_address: 'no-reply@figma.com',
    cancellation_url: 'https://www.figma.com/settings',
    is_demo: true,
  },
  {
    name: 'Duolingo Super',
    domain: 'duolingo.com',
    category: 'Education',
    amount: 6.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 2).toISOString().split('T')[0],
    status: 'trial',
    trial_ends_at: addDays(new Date(), 2).toISOString().split('T')[0],
    first_detected_at: subMonths(new Date(), 1).toISOString(),
    email_address: 'hello@duolingo.com',
    cancellation_url: 'https://www.duolingo.com/settings/subscriptions',
    is_demo: true,
  },
  {
    name: 'The New York Times',
    domain: 'nytimes.com',
    category: 'News',
    amount: 17.00,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 22).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 5).toISOString(),
    email_address: 'nytdirect@nytimes.com',
    cancellation_url: 'https://myaccount.nytimes.com/seg/cancel',
    is_demo: true,
  },
  {
    name: 'Headspace',
    domain: 'headspace.com',
    category: 'Health',
    amount: 12.99,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 15).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 7).toISOString(),
    email_address: 'help@headspace.com',
    cancellation_url: 'https://www.headspace.com/subscriptions',
    is_demo: true,
  },
  {
    name: 'Amazon Web Services',
    domain: 'aws.amazon.com',
    category: 'Cloud',
    amount: 47.32,
    currency: 'USD',
    billing_cycle: 'monthly',
    next_payment_date: addDays(new Date(), 28).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 12).toISOString(),
    email_address: 'aws-billing@amazon.com',
    cancellation_url: 'https://console.aws.amazon.com/billing/',
    is_demo: true,
  },
  {
    name: 'Dropbox Plus',
    domain: 'dropbox.com',
    category: 'Cloud',
    amount: 119.88,
    currency: 'USD',
    billing_cycle: 'annual',
    next_payment_date: addMonths(new Date(), 4).toISOString().split('T')[0],
    status: 'active',
    trial_ends_at: null,
    first_detected_at: subMonths(new Date(), 8).toISOString(),
    email_address: 'no-reply@dropbox.com',
    cancellation_url: 'https://www.dropbox.com/account/plan',
    is_demo: true,
  },
];
